name = "safe174th"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "safe174th"
database_id = "dd4d7be3-cf84-4999-981e-9553e5d4ae28"
